spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
# spring.datasource.url=${JDBC_DATABASE_URL\:jdbc\:h2\:mem\:pftgriddbcloud}
# spring.datasource.username=${JDBC_DATABASE_USERNAME\:sa}
# spring.datasource.password=${JDBC_DATABASE_PASSWORD\:}
# spring.datasource.hikari.connection-timeout=30000
# spring.datasource.hikari.maximum-pool-size=10
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.open-in-view=false
# spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
# spring.jpa.properties.hibernate.id.new_generator_mappings=true

error.handling.http-status-in-json-response=true
error.handling.exception-logging=NO_LOGGING
error.handling.full-stacktrace-http-statuses=5xx
error.handling.log-levels.5xx=ERROR
error.handling.codes.UserIdValid=USER_ID_VALID
error.handling.codes.UserEmailUnique=USER_EMAIL_UNIQUE
error.handling.codes.CategoryIdValid=CATEGORY_ID_VALID
error.handling.codes.CategoryNameUnique=CATEGORY_NAME_UNIQUE
error.handling.codes.TransactionIdValid=TRANSACTION_ID_VALID
spring.mvc.format.date=yyyy-MM-dd
spring.mvc.format.date-time=yyyy-MM-dd'T'HH\:mm\:ss
spring.mvc.format.time=HH\:mm\:ss

spring.thymeleaf.cache=false
spring.web.resources.chain.cache=false

# Logging
logging.level.org.springframework=INFO
logging.level.org.springframework.web=DEBUG
# logging.level.org.springframework.context.annotation=TRACE
logging.level.org.springframework.security=DEBUG

# GridDB Configuration
griddbcloud.base-url=${GRIDDBCLOUD_BASE_URL}
griddbcloud.auth-token=${GRIDDBCLOUD_AUTH_TOKEN}
